In [1]:
from sklearnex import patch_sklearn

patch_sklearn()

import pandas as pd
from ipynb.fs.defs.preprocessing import get_data
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler, ADASYN, SMOTE
from util import summary

Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)

In [2]:
X_train, X_test, y_train, y_test = get_data(use_val=False, test_size=0.3)

In [3]:
X_train

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
215379,140045.0,-2.702821,-3.419735,-1.134737,-2.918930,-0.956281,0.320069,3.553486,-0.465920,-1.367474,...,1.945383,0.370625,-0.320385,1.720828,-1.234269,1.586650,0.017388,-0.352727,0.104559,954.27
120134,75720.0,1.302833,-0.255699,0.165476,0.649424,-0.558770,-0.361895,-0.238675,-0.058507,-0.857121,...,-0.661727,-0.379284,-0.478606,-0.025531,0.033080,0.622888,-0.226874,0.044939,0.013552,6.00
145695,87137.0,-1.055158,0.146735,1.098594,-0.708571,0.053689,-0.689251,-0.322407,0.480596,0.425362,...,-0.050497,0.417039,1.092653,-0.263530,-0.095338,-0.247609,0.137567,0.063740,0.010777,1.00
101006,67698.0,1.148034,0.346297,0.417834,1.213868,-0.351031,-1.109568,0.365078,-0.338455,-0.242111,...,0.007469,0.087264,0.273518,-0.108201,0.761831,0.674175,-0.357113,0.015446,0.033174,42.81
160763,113616.0,2.119046,-1.677256,-0.759965,-1.368180,-1.673078,-0.964254,-1.080627,-0.244152,-1.026756,...,-0.301690,-0.112187,-0.005810,0.187089,0.016863,-0.302629,-0.187873,0.001935,-0.032618,100.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226378,144604.0,2.055781,0.213305,-2.871349,0.897046,1.567990,-0.447251,1.043763,-0.411362,-0.473665,...,-0.156216,0.299864,0.949033,-0.442672,-1.389229,1.005570,-0.129584,-0.064367,-0.095020,50.00
256753,157842.0,1.874475,-1.926058,0.462381,-0.553780,-1.761380,1.422006,-2.159373,0.590852,1.418734,...,0.141293,0.361984,1.277097,0.035403,0.368430,-0.253272,-0.010638,0.072031,-0.026689,92.20
269169,163568.0,-0.370893,1.201703,-1.662683,0.556854,1.534893,-0.285533,0.880982,0.269601,-0.912073,...,-0.106611,0.276806,0.792500,-0.140757,-1.461992,-0.629129,-0.450162,0.265973,0.235045,8.00
136585,81775.0,-0.310002,0.385148,1.569044,-0.156947,0.219196,-0.837982,0.611446,-0.297265,-0.687303,...,0.289339,0.203071,0.705392,-0.061054,0.639450,-0.640064,0.996090,-0.095860,-0.074286,19.90
233395,147548.0,-1.234129,1.702568,-1.141789,-0.692898,0.293965,-0.699735,0.376199,0.483144,0.104006,...,0.029580,0.387350,1.351566,-0.024509,-0.525842,-0.652717,-0.240358,0.044320,0.080752,0.89

In [4]:
clf = Pipeline([("scaler", StandardScaler()), ("logreg", LogisticRegression())])
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
summary(y_test, y_pred)

accuracy_score 0.9992860737567735
recall_score: 0.6551724137931034
precision_score: 0.8962264150943396
f1_score 0.7569721115537849
COnfusion matrix: [[85287    11]
 [   50    95]]

In [5]:
ros = RandomOverSampler(random_state=42, sampling_strategy=0.01)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
clf = Pipeline([("scaler", StandardScaler()), ("logreg", LogisticRegression())])
clf.fit(X_resampled, y_resampled)
y_pred = clf.predict(X_test)
summary(y_test, y_pred)
X_resampled

accuracy_score 0.9993211848834895
recall_score: 0.8206896551724138
precision_score: 0.7880794701986755
f1_score 0.8040540540540541
COnfusion matrix: [[85266    32]
 [   26   119]]

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,140045.0,-2.702821,-3.419735,-1.134737,-2.918930,-0.956281,0.320069,3.553486,-0.465920,-1.367474,...,1.945383,0.370625,-0.320385,1.720828,-1.234269,1.586650,0.017388,-0.352727,0.104559,954.27
1,75720.0,1.302833,-0.255699,0.165476,0.649424,-0.558770,-0.361895,-0.238675,-0.058507,-0.857121,...,-0.661727,-0.379284,-0.478606,-0.025531,0.033080,0.622888,-0.226874,0.044939,0.013552,6.00
2,87137.0,-1.055158,0.146735,1.098594,-0.708571,0.053689,-0.689251,-0.322407,0.480596,0.425362,...,-0.050497,0.417039,1.092653,-0.263530,-0.095338,-0.247609,0.137567,0.063740,0.010777,1.00
3,67698.0,1.148034,0.346297,0.417834,1.213868,-0.351031,-1.109568,0.365078,-0.338455,-0.242111,...,0.007469,0.087264,0.273518,-0.108201,0.761831,0.674175,-0.357113,0.015446,0.033174,42.81
4,113616.0,2.119046,-1.677256,-0.759965,-1.368180,-1.673078,-0.964254,-1.080627,-0.244152,-1.026756,...,-0.301690,-0.112187,-0.005810,0.187089,0.016863,-0.302629,-0.187873,0.001935,-0.032618,100.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201002,68357.0,1.232604,-0.548931,1.087873,0.894082,-1.433055,-0.356797,-0.717492,0.003167,-0.100397,...,-0.576274,-0.448671,-0.517568,0.012833,0.699217,0.527258,-0.322607,0.080805,0.035427,19.59
201003,43369.0,-3.365319,2.426503,-3.752227,0.276017,-2.305870,-1.961578,-3.029283,-1.674462,0.183961,...,-0.036837,2.070008,-0.512626,-0.248502,0.126550,0.104166,-1.055997,-1.200165,-1.012066,88.00
201004,28242.0,-2.787248,-0.071340,-1.505288,3.361777,-3.357422,0.565835,0.303653,0.966914,-2.245882,...,1.607397,0.882940,-0.246202,1.752227,0.219925,0.156282,-0.265894,0.220694,0.256077,730.86
201005,26899.0,-21.885434,12.930505,-24.098872,6.203314,-16.466099,-4.459842,-16.519836,14.535565,-3.897022,...,1.611998,1.762232,-1.579055,-0.951043,0.134565,1.507110,-0.222671,1.527655,0.453699,99.99
201006,155554.0,-1.040067,3.106703,-5.409027,3.109903,-0.887237,-2.497522,-2.073347,0.639818,-3.013331,...,1.054390,0.773961,0.214868,-0.184233,-0.284091,0.493467,0.732329,0.675067,0.337076,94.82

In [6]:
X_train

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
215379,140045.0,-2.702821,-3.419735,-1.134737,-2.918930,-0.956281,0.320069,3.553486,-0.465920,-1.367474,...,1.945383,0.370625,-0.320385,1.720828,-1.234269,1.586650,0.017388,-0.352727,0.104559,954.27
120134,75720.0,1.302833,-0.255699,0.165476,0.649424,-0.558770,-0.361895,-0.238675,-0.058507,-0.857121,...,-0.661727,-0.379284,-0.478606,-0.025531,0.033080,0.622888,-0.226874,0.044939,0.013552,6.00
145695,87137.0,-1.055158,0.146735,1.098594,-0.708571,0.053689,-0.689251,-0.322407,0.480596,0.425362,...,-0.050497,0.417039,1.092653,-0.263530,-0.095338,-0.247609,0.137567,0.063740,0.010777,1.00
101006,67698.0,1.148034,0.346297,0.417834,1.213868,-0.351031,-1.109568,0.365078,-0.338455,-0.242111,...,0.007469,0.087264,0.273518,-0.108201,0.761831,0.674175,-0.357113,0.015446,0.033174,42.81
160763,113616.0,2.119046,-1.677256,-0.759965,-1.368180,-1.673078,-0.964254,-1.080627,-0.244152,-1.026756,...,-0.301690,-0.112187,-0.005810,0.187089,0.016863,-0.302629,-0.187873,0.001935,-0.032618,100.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226378,144604.0,2.055781,0.213305,-2.871349,0.897046,1.567990,-0.447251,1.043763,-0.411362,-0.473665,...,-0.156216,0.299864,0.949033,-0.442672,-1.389229,1.005570,-0.129584,-0.064367,-0.095020,50.00
256753,157842.0,1.874475,-1.926058,0.462381,-0.553780,-1.761380,1.422006,-2.159373,0.590852,1.418734,...,0.141293,0.361984,1.277097,0.035403,0.368430,-0.253272,-0.010638,0.072031,-0.026689,92.20
269169,163568.0,-0.370893,1.201703,-1.662683,0.556854,1.534893,-0.285533,0.880982,0.269601,-0.912073,...,-0.106611,0.276806,0.792500,-0.140757,-1.461992,-0.629129,-0.450162,0.265973,0.235045,8.00
136585,81775.0,-0.310002,0.385148,1.569044,-0.156947,0.219196,-0.837982,0.611446,-0.297265,-0.687303,...,0.289339,0.203071,0.705392,-0.061054,0.639450,-0.640064,0.996090,-0.095860,-0.074286,19.90
233395,147548.0,-1.234129,1.702568,-1.141789,-0.692898,0.293965,-0.699735,0.376199,0.483144,0.104006,...,0.029580,0.387350,1.351566,-0.024509,-0.525842,-0.652717,-0.240358,0.044320,0.080752,0.89

In [ ]:
ros = SMOTE(random_state=42, sampling_strategy=0.01, k_neighbors=5)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
clf = Pipeline([("scaler", StandardScaler()), ("logreg", LogisticRegression())])
clf.fit(X_resampled, y_resampled)
y_pred = clf.predict(X_test)
summary(y_test, y_pred)

accuracy_score 0.9993328885923949
recall_score: 0.7793103448275862
precision_score: 0.8188405797101449
f1_score 0.7985865724381626
COnfusion matrix: [[85273    25]
 [   32   113]]

In [39]:
ros = ADASYN(random_state=42, sampling_strategy=0.01)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
clf = Pipeline([("scaler", StandardScaler()), ("logreg", LogisticRegression())])
clf.fit(X_resampled, y_resampled)
y_pred = clf.predict(X_test)
summary(y_test, y_pred)

accuracy_score 0.9992977774656788
recall_score: 0.7655172413793103
precision_score: 0.8102189781021898
f1_score 0.7872340425531915
COnfusion matrix: [[85272    26]
 [   34   111]]